---
- name: Validate Network State
  hosts: wan
  connection: httpapi
  gather_facts: false
  tasks:

    - name: Validate Network State
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state

